title = "TOML file for bankcsv program."
# This file contains data used by the bankcsv file, like category names, short names, et al

categories = [
    "Groceries",
    "Gas",
    "House Hold",
    "Dining Out",
    "Subscriptions",
    "Utilites",
    "Perscriptsion",
    "Medical",
    "Taxes", 
    "Others",
    "Deposit",
    "Check",
]

short_names = [
    "Food Lion",
    "Ingles",
    "CVS",
    "Pharmacy",
    "Lowes Home Improvement",
    "Saines",
    "Amazon",
    "Bricktree",
    "Untapped",
    "Wells Fargo",
    "Emerald Commons",
    "Consumer Cellular",
    "Bridgecrest",
    "Food Court",
    "Wal-Mart",
    "DUNKIN",
]

subscriptions = [
    "Netflix",
    "Hulu",
    "Prime",
    "Spotify",
    "Apple",
    "Apple Music"
]
