[package]
name = "bankcsv"
version = "0.1.0"
edition = "2021"


[dependencies]
csv = "1.1.6"
serde = "1.0.136"
serde_derive = "1.0.136"
serde_json = "1.0.105"
serde_yaml = "0.9.17"
structopt = "0.3.26"

